name: Reusable workflow to run smoke tests

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      kubernetesVersion:
        required: true
        type: string
      kindImage:
        required: true
        type: string
permissions:
  contents: read

jobs:
  smoke-tests:
    name: Validate k8s-${{ inputs.kubernetesVersion }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Setup Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: "1.23"

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install curl make ca-certificates gcc libc-dev wget -y
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 1

      - name: Create k8s ${{ inputs.kubernetesVersion }} Kind Cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          node_image: ${{ inputs.kindImage }}
          cluster_name: smoke-tests-cluster-${{ inputs.kubernetesVersion }}

      - name: Run smoke test
        run: make smoke-test

      - name: Upload test logs
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        if: ${{ always() }}
        with:
          name: smoke-test-logs ${{ inputs.runs-on }}-${{ inputs.kubernetesVersion }}
          path: "${{ github.workspace }}/**/*.log"
          if-no-files-found: ignore
